server:
  port: 8081
  servlet:
    context-path: "/rpt"

spring:
  application:
    name: reporting-api-service

reporting:
  queues:
    control-queue-name: REA_QUEUE
    datagen-queue-name: DATA_GEN_QUEUE
    rpt-queue-name: REPORT_GEN_QUEUE
    distro-queue-name: DISTRIBUTION_QUEUE